#!/usr/bin/env bash

function display_usage() {
    echo "Usage: $0 {IP_ADDRESS}"
}

# Check if an argument is provided
if [ $# -eq 0 ]; then
    display_usage
    exit 1
fi

# Extract the IP address from the argument
ip_address=$1

# Check if the provided argument is a valid IP address
if ! [[ "$ip_address" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid IP address format."
    display_usage
    exit 1
fi

# Function to ping the IP address five times
function ping_ip() {
    echo "Pinging $ip_address 5 times..."
    ping -c 5 "$ip_address"
}

# Call the ping_ip function
ping_ip
