#!/usr/bin/env bash

# Check if the script is being run with root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run the script with root privileges (sudo)."
  exit 1
fi

# Function to configure /etc/hosts
function configure_hosts() {
    echo "127.0.0.2 localhost" >> /etc/hosts
    echo "8.8.8.8 facebook.com" >> /etc/hosts
    echo "Hosts file updated successfully."
}

# Function to configure DNS resolver settings
function configure_dns_resolver() {
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    echo "DNS resolver settings updated successfully."
}

# Call the functions to make the configurations
configure_hosts
configure_dns_resolver
